### ISSUE TITLE
Obsidian gets stuck indexing for a long time (forever?)

### ISSUE THREAD

**Issue by kyounes** [ljcoder2015/obsidian-excel-plus#11]
This is probably related to bug #4, excel-plus version 1.1.4. Obsidian doesn't crash anymore, but it never stops indexing and eats up 25% of my CPU continuously  when I have a couple of spreadsheets in the vault. One of them is just a small sheet, the other has 5 sheets with ~100 rows per sheet.

This immediately stops when I remove the spreadsheets from the vault.

I'll try to troubleshoot a bit more, but for now this prevents me from using excel-plus...

**Comment by kyounes** [comment]
Attaching a test spreadsheet that shows the problem. This has only one sheet, but still gets stuck in indexing mode, seemingly forever. If I delete column I (the letter 'i'), then close the vault and re-open it, the issue goes away. Still using excel-plus v1.1.4 , obsidian 1.5.12

[Test.univer.md](https://github.com/ljcoder2015/obsidian-excel-plus/files/15424712/Test.univer.md)

**Comment by ljcoder2015** [comment]
fix [1.1.6](https://github.com/ljcoder2015/obsidian-excel-plus/releases/tag/1.1.6)

**Comment by kyounes** [comment]
Correction. Indexing completed after 2-3 minutes. I'll test some more and update if necessary.

**Comment by ljcoder2015** [comment]
After updating the plugin, you need to reopen this file and then restart Obsidian.

Make sure the content is within a code block.

**Comment by bigfoot31** [comment]
I have a excel file with images of 35MB size. Keeps crashing the obsidian app on IOS
