### ISSUE TITLE
Command support

### ISSUE THREAD

**Issue by Accelsnow** [ljcoder2015/obsidian-excel-plus#2]
This might be more of a question rather than an issue. I can't seem to find a command associated with excel-plus in the command palette. I am currently relying on the side panel "Create Excel File" to create excel sheets. I am wondering if there is a command that I am not aware of or is that WIP. It would be helpful to have it for ease-of-use.

Obsidian v1.5.12
excel-plus 1.0.0

**Comment by ljcoder2015** [comment]
[excel-plus 1.0.2](https://github.com/ljcoder2015/obsidian-excel-plus/releases/tag/1.0.2) support
