### ISSUE TITLE
References across sheets don't work

### ISSUE THREAD

**Issue by kyounes** [ljcoder2015/obsidian-excel-plus#3]
References across sheets (of the same document) don't seem to work. For example, a formula in sheet2 that says ='Sheet1':!B7 seems to be accepted, but then it gets removed and the cell is blank.

**Comment by ljcoder2015** [comment]
fix [1.1.3](https://github.com/ljcoder2015/obsidian-excel-plus/releases/tag/1.1.3)

**Comment by kyounes** [comment]
Thank you, confirmed working in 1.1.4
