### ISSUE TITLE
Obsidian crashes while trying to index a spreadsheet

### ISSUE THREAD

**Issue by kyounes** [ljcoder2015/obsidian-excel-plus#4]
I created a spreadsheet with 5 sheets, about 150 lines per sheet with mostly numbers and text. When I navigate away from the spreadsheet and Obsidian attempts to index it, it completely locks up and I have to end the task from Windows Task Manager.

**Comment by ljcoder2015** [comment]
This issue was optimized in version 1.1.4

**Comment by kyounes** [comment]
Thank you, confirmed working
