### ISSUE TITLE
Unable to import from excel, libre office, or anything

### ISSUE THREAD

**Issue by kyounes** [ljcoder2015/obsidian-excel-plus#8]
Not sure if this is a bug or a feature request. I read on the web site that I should be able to import a spreadsheet from excel but I cannot find a way to do it. Attached screen shots with command menus.
![image](https://github.com/ljcoder2015/obsidian-excel-plus/assets/6969634/62fa7e4a-c570-447f-ac92-c1bae794f18f)

![image](https://github.com/ljcoder2015/obsidian-excel-plus/assets/6969634/bc8fb2bd-f83c-4f01-a3df-f3d50cd78090)

**Comment by ljcoder2015** [comment]
In the Univer framework, the import feature is a paid option, so we do not support it.

**Comment by kyounes** [comment]
Hm. I didn't know this, it's disappointing. Feel free to close this then, maybe consider adding it (or some usable subset) as a future feature...
